- hosts: 127.0.0.1
  connection: local
  vars:
  - vault_addr: https://vault-vault.apps.52.232.124.18.xip.io
  - ssh_mount_point: ssh
  - allowed_cidr_list: "0.0.0.0/0"
  - allowed_roles: "*"
  - tls_skip_verify: true
  roles:
  - vault-ssh-helper
