---
- name: Download and unzip vault-ssh-helper
  unarchive:
    src: 'https://releases.hashicorp.com/vault-ssh-helper/0.1.4/vault-ssh-helper_0.1.4_linux_amd64.zip'
    dest: /usr/local/bin
    remote_src: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
